Fixed apptainer template

diff --git a/pism_terra/templates/chinook-apptainer.j2 b/pism_terra/templates/chinook-apptainer.j2
--- a/pism_terra/templates/chinook-apptainer.j2
+++ b/pism_terra/templates/chinook-apptainer.j2
@@ -8,13 +8,19 @@
 #SBATCH --mail-type=FAIL
 #SBATCH --output="{{ output_path }}/pism.%j"
 
-module list
+module purge
+module load intel-compilers/2023.1.0 impi/2021.9.0
+
+export container=$HOME/pism-dev.sif
+if [ ! -f "${container}" ]; then
+    echo "Container ${container} not found." >&2
+    exit 1
+fi
+echo "Using container ${container}"
 
 umask 007
 
 cd $SLURM_SUBMIT_DIR
-
-srun -l /bin/hostname | sort -n | awk '{print $2}' > ./nodes_$SLURM_JOBID
 
 ulimit -l unlimited
 ulimit -s unlimited
